version: '2'
# Production
services:
  exim:
    build:
      context: ./containers/exim
      dockerfile: ./Dockerfile
    ports:
      - "25:25"
    volumes:
      - ./CONF/exim:/etc/exim

  clamav:
    build:
      context: ./containers/clamav
      dockerfile: ./Dockerfile
    ports:
      - "3310"
    environment:
      - DEBUG_MODE=""
    volumes:
      - ./DATA/clamav:/var/lib/clamav

  rspamd:
    build:
      context: ./containers/rspamd
      dockerfile: ./Dockerfile
    ports:
      - "11332"
      - "11334:11334"
    volumes:
      - ./DATA/rspamd:/var/lib/rspamd

# other stuff
