version: '2'
# Production
services:
  exim:
    build:
      context: ./containers/exim
      dockerfile: ./Dockerfile
    ports:
      - "25:25"

  clamav:
    build:
      context: ./containers/clamav
      dockerfile: ./Dockerfile
    ports:
      - "3310"

  rspamd:
    build:
      context: ./containers/rspamd
      dockerfile: ./Dockerfile
    ports:
      - "11332"
      - "11334"

# other stuff
