version: '2'
# Production
services:
  exim:
    build:
      context: ./containers/exim
      dockerfile: ./Dockerfile
    ports:
      - "25:25"
    volumes:
      - ${PWD}/CONF/exim:/etc/exim
    depends_on:
      - mariadb
      - rspamd

  clamav:
    build:
      context: ./containers/clamav
      dockerfile: ./Dockerfile
    ports:
      - "3310"
    environment:
      - DEBUG_MODE=""
    volumes:
      - ${PWD}/DATA/clamav:/var/lib/clamav

  rspamd:
    build:
      context: ./containers/rspamd
      dockerfile: ./Dockerfile
    ports:
      - "11332"
      - "11334:11334"
    volumes:
      - ${PWD}/DATA/rspamd:/var/lib/rspamd
    depends_on:
      - clamav

  mariadb:
    build:
      context: ./containers/db
      dockerfile: ./Dockerfile
    ports:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'

  adminer:
    image: adminer:standalone
    ports:
      - 9090:8080
    depends_on:
      - mariadb
    links:
      -  mariadb:db

volumes:
  mariadb:
